# Generated by Django 4.1.6 on 2023-02-04 20:59

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0002_trains_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Trains',
            new_name='Workouts',
        ),
    ]
